# Dataset configs
RAW_AUDIO_PATH = "raw_audio"
SAVE_PATH = "ViSEDia"
MAX_LENGTH = 30
MIN_DURATION = 3
N_CONSECUTIVE_UTTERANCE = 3
PAD_DURATION = 0.5
ORIG_SAMPLE_RATE = 22050
TARGET_SAMPLE_RATE = 16000

